### ISSUE TITLE
KeyError: "name='xs', domain=None, path=None"

### ISSUE THREAD

**Issue by RexsyBima** [Strvm/meta-ai-api#17]
when i ran the code from either python or jupiter notebook with these lines

``` python
from meta_ai_api import MetaAI

ai = MetaAI(fb_email="someemail", fb_password="somepassword")
response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
print(response)
```

i got

```

Traceback (most recent call last):
  File "d:\Python\metaaitest\main.py", line 185, in <module>
    funcGenNews(news)
  File "d:\Python\metaaitest\main.py", line 92, in funcGenNews
    ai = CustomMetaAI()
  File "d:\Python\metaaitest\src\meta_ai.py", line 19, in __init__
    super().__init__(fb_email=fb_email, fb_password=fb_password)
  File "D:\Python\tiktok-content-news-AI\.venv\lib\site-packages\meta_ai_api\main.py", line 50, in __init__
    self.cookies = self.get_cookies()
  File "D:\Python\metaaitest\.venv\lib\site-packages\meta_ai_api\main.py", line 316, in get_cookies
    fb_session = get_fb_session(self.fb_email, self.fb_password)
  File "D:\Python\metaaitest\.venv\lib\site-packages\meta_ai_api\utils.py", line 157, in get_fb_session
    "xs": session.cookies["xs"],
  File "D:\Python\metaaitest\.venv\lib\site-packages\requests\cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "D:\Python\metaaitest\.venv\lib\site-packages\requests\cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='xs', domain=None, path=None"

```

im using vpn to avoid region block, yesterday was fine as butter. idk why it happens

**Comment by Strvm** [comment]
Hi, are you able to access it with your VPN on a browser?

**Comment by RexsyBima** [comment]
Yup i can, im using windscribe

**Comment by Strvm** [comment]
> Yup i can, im using windscribe

And could you try without authenticating and tell me what do you get

**Comment by RexsyBima** [comment]
i got 

`Exception: Unable to obtain a valid response from Meta AI. Try again later.`

just want to make sure, is it still working on your end?

**Comment by RexsyBima** [comment]
im kinda worried it has something to do with my account, i did something in my facebook app which is that i created new fan page profile... ill try to create dummy fresh facebook account just in case, but not now, will try to do it tomorrow

**Comment by Strvm** [comment]
Not sure it has anything to do with your FB account since it should also work without authenticating

**Comment by RexsyBima** [comment]
what python version are you using?

**Comment by Strvm** [comment]
The test was running 3.8, but that shouldn't really matter

**Comment by RexsyBima** [comment]
So um, interesting here. i do have a dummy account i didnt use back then. when im using the dummy account i got this error instead of key error

`
Traceback (most recent call last):
  File "d:\Python\meta-ai-api\test.py", line 3, in <module>
    ai = MetaAI(fb_email="apras3177@gmail.com", fb_password="M67a;C5Uq8xeBp6")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\main.py", line 50, in __init__
    self.cookies = self.get_cookies()
                   ^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\main.py", line 316, in get_cookies
    fb_session = get_fb_session(self.fb_email, self.fb_password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\utils.py", line 210, in get_fb_session
    next_url = response.headers["Location"]
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'
`

same code, different email and password

**Comment by RexsyBima** [comment]
so i use some dummy facebook account here, same code, but now i got KeyError instead
`
Traceback (most recent call last):
  File "d:\Python\meta-ai-api\test.py", line 3, in <module>
    ai = MetaAI(fb_email="xxxx", fb_password="xxxx")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\main.py", line 50, in __init__
    self.cookies = self.get_cookies()
                   ^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\main.py", line 316, in get_cookies
    fb_session = get_fb_session(self.fb_email, self.fb_password)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\meta_ai_api\utils.py", line 210, in get_fb_session
    next_url = response.headers["Location"]
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\Python\meta-ai-api\.venv\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'location'
`
