### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by 0wwafa** [Strvm/meta-ai-api#43]
```
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from meta_ai_api import MetaAI
>>> 
>>> ai = MetaAI()
>>> response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 2/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 3/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 4/3.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
  File "/usr/local/lib/python3.10/dist-packages/meta_ai_api/main.py", line 220, in retry
    raise Exception(
Exception: Unable to obtain a valid response from Meta AI. Try again later.
```

**Comment by Strvm** [comment]
Probably related to where you are running the scripts, if its in a datacenter, Meta is probably blocking you
