### ISSUE TITLE
Exception: Unable to obtain a valid response from Meta AI. Try again later.

### ISSUE THREAD

**Issue by NAUGHTY-BRAND** [Strvm/meta-ai-api#46]
meta-ai-api$ python a.py
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 2/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 3/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 4/3.
Traceback (most recent call last):
  File "/home/runner/meta-ai-api/a.py", line 4, in <module>
    response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 218, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/meta-ai-api/.pythonlibs/lib/python3.12/site-packages/meta_ai_api/main.py", line 220, in retry
    raise Exception(
Exception: Unable to obtain a valid response from Meta AI. Try again later.

what this err 🎭

**Comment by Jacob1802** [comment]
I was able to fix this by just creating a new instance. I assume this has to do with the context window, so if you login it might increase the size but I haven't tested it
