### ISSUE TITLE
Error in responding

### ISSUE THREAD

**Issue by AbdulRahman-Muhammad** [Strvm/meta-ai-api#51]
Hi,
I'm from Egypt and this country is blocked so I used a VPN Service changed my location into US, Washington 
After that I got,
```traceback
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 1/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 2/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 3/3.
WARNING:root:Was unable to obtain a valid response from Meta AI. Retrying... Attempt 4/3.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/nanolgpt.py", line 4, in <module>
    response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 174, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 195, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 174, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 195, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 174, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 195, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 174, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 195, in retry
    return self.prompt(message, stream=stream, attempts=attempts + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 174, in prompt
    return self.retry(message, stream=stream, attempts=attempts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/meta_ai_api/main.py", line 197, in retry
    raise Exception(
Exception: Unable to obtain a valid response from Meta AI. Try again later.
```

Code that I have used:

```python
from meta_ai_api import MetaAI

ai = MetaAI()
response = ai.prompt(message="Whats the weather in San Francisco today? And what is the date?")
print(response)
 ```

**Comment by AbdulRahman-Muhammad** [comment]
@Strvm Please, reply with the solution I'm using termux

**Comment by Strvm** [comment]
Hi @AbdulRahman-Muhammad , this is most likely due FB blocking your VPN. Might have to try other VPNs/Proxies to see if that can work.
